---
title: "Teaching"
description: |
  Uh oh, this site is under construction.  Please check back after Kyle has done some teaching.
site: distill::distill_website
---

<div>
  <h3 class="taHeading">Teaching Assistant</h3>
  <p class="taList">
    <ul>
      <li><a href="https://www.cosmos.uci.edu/welcome-to-your-new-website/cluster-1-data-science-in-health-sciences/">UCI COSMOS Exploring the Application of Data Science in the Health Sciences</a> (July 2021)
        <ul>
          <li> Professors: Dr. <a href="https://mdogucu.ics.uci.edu/">Mine Dogucu</a> and Dr. <a href="https://www.ics.uci.edu/~babaks/">Babak Shahbaba </a></li>
          <li>This cluster explores how data science can be used to better understand and treat human health conditions, with the goal of saving lives.</li>
        </ul>
      </li>
      <li><a href="http://catalogue.uci.edu/allcourses/stats/">STATS 120A Introduction to Probability and Statistics I</a> (Summer 2021)
        <ul>
          <li>Professor: Dr. <a href="https://www.stat.uci.edu/faculty/koko-gulesserian/">Koko Gulesserian</a></li>
          <li>Introduction to basic principles of probability and statistical inference. Axiomatic definition of probability, random variables, probability distributions, expectation.</li>
        </ul>
      </li>
      <li><a href="http://catalogue.uci.edu/allcourses/stats/">STATS 7 Basic Statistics</a>.(Summer 2020)  
        <ul>
          <li>Professor: Dr. <a href="https://maryryan.netlify.app/">Mary Ryan</a></li>
          <li>Introduces basic inferential statistics including confidence intervals and hypothesis testing on means and proportions, t-distribution, Chi Square, regression and correlation. F-distribution and nonparametric statistics included if time permits.</li>
        </ul>
      </li>
      <li>STATS 7 Basic Statistics (Summer 2018).  
      <ul><li>Professor: Dr. <a href="https://profiles.sc-ctsi.org/michelle.nuno">Michelle Nuno</a></li></ul></li>
    </ul></li>
  </p>
    
  <h3 class="guestTeachingHeading">Guest Teaching</h3>
  <p class="guestTeachList">
    <ul>
      <li>Quantitative Methods for Public Policy at Liberty University (November 2020)
        <ul>
        <li>Professor: Dr. <a href="https://www.liberty.edu/government/faculty/kahlib-fischer/">Kahlib Fischer</a></li>
        <li>Discussion on the process of question development and preparing for data collection.</li>
      </ul>
      </li>
      <li>Quantitative Methods for Public Policy at Liberty University (December 2020)
      <ul>
        <li>Professor: Dr. Kahlib Fischer</li>
        <li>Discussion on the process of performing a statistical analysis.</li>
      </ul>
      </li>
      <li>Quantitative Methods for Public Policy at Liberty University (January-March 2021)
      <ul>
        <li>Professor: Dr. Kahlib Fischer</li>
        <li>Working with three project groups to refine their research questions and hypotheses.</li>
      </ul>
      </li>
    </ul>
  </p>
  
  <h3 class="teachHeading">Teaching</h3>
  <p class="teachList">
    <ul>
      <li>None yet</li>
    </ul>
  </p>
  
</div>


<div>
<h3 class="otherTeachHeading">Additional Teaching Endeavors</h3>
  <p class="otherTeachWork">Kyle has started developing two resources for teaching introductory statistics.  The original ideas and (much appreciated) guidance come from <a href="https://mdogucu.ics.uci.edu/">Dr. Mine Dogucu</a>.  The goal is to turn these projects into useful tools for teaching students the basics of statistics.
    <ul style="list-style-type:none;">
      <li><a href="https://github.com/kcon13/introTeach">R Package</a></li>
      <li><a href="https://github.com/kcon13/introTeach-shiny">R Shiny</a></li>
    </ul>
  </p>
</div>

<div class="TeachWork">
  <p>The two projects currently work together to help students calculate z-scores, t-scores, quantiles, and p-values from the information that will be given in a typical introductory question.  There is also an option to visualize the distribution and area to which the probability corresponds.  The projects are only in the very formative stages, with many more ideas for adding to them.  Some of the goals include:
    <ol>
      <li>Guide for choosing the right test</li>
      <li>Guide for using the right formula</li>
      <li>Step-by-step solutions for the z- and t-score questions</li>
      <li>Rejection regions on visualization plot</li>
      <li>Multiple plots for thinking about conversions from "original units" to "standard units"</li>
      <li>Expanding to two-sample cases</li>
      <li>Expanding to other introductory topics</li>
      <li>Many more ideas to be sorted through</li>
    </ol>
  </p>
</div>