---
title: "Tutoring"
description: |
  Kyle actively tutors in statistics and mathematics.
site: distill::distill_website
---



<div>
  <p class="tutorIntro">
    Kyle has over 10 years of tutoring experience.  He has refined his 1-on-1 tutoring technique to emphasize using the student's own learning style to maximize their knowledge base in the subject.  Thus, when a faced with a challenging question, students are prepared to think through the question in their own terms.  If you are looking for an experienced, personable tutor who will focus on your learning, then reach out to Kyle by sending him an email: <a href="mailto:krconnif@uci.edu">krconnif@uci.edu</a>.
  </p>
</div>
<div>
  <h5>Current number of students for winter 2021: 10 </h5>
  <h6>Student count last updated: 3/22/2021</h6>
</div>



<div class="tutorResume">
  <h3>Resume</h3>
  <ul>
    <li class="job-title"><strong>Independent Tutor</strong> (2012-Current)
      <ul >
      <li class="job-description">I've met 1-on-1 with students for several years.  I've worked completely independently with students (UCI page below), as well as through tutoring systems (the second and third links below).
        <ul>
          <li><a href="https://www.stat.uci.edu/tutoring-resources/">UCI Stats Department</a></li>
          <li><a href="https://takelessons.com/profile/kyle-c31?service=math&online=1">TakeLessons</a></li>
          <li><a href="https://www.wyzant.com/match/tutor/86985535">Wyzant</a></li>
        </ul>
        </li>
      </ul>
      </li>
          <li class="job-title"><strong>Introduction to Statistics Teaching Assistant</strong> (2018, 2020)
      <ul>
        <li class="job-description">Worked with the teacher to help teach introductory statistics during the shortened summer sessions.  I taught review sessions, created test questions, checked homework and lab assignments, and mostly helped answer student questions about the material, homeworks, and labs.</li>
      </ul></li>
    <li class="job-title"><strong>St. Norbert College Multicultural Center Tutor</strong> (2012-2013)
      <ul>
        <li class="job-description">Similar to holding office hours, I sat in a large room and helped my multicultural peers with all levels of math from algebra through multivariate calculus, introductory economics, writing/editing, and a few other introductory classes I was also taking. </li>
      </ul>
    </li>
    <li class="job-title"><strong>Boy's & Girl's Club Tutor</strong> (2012-2013)
      <ul>
        <li class="job-description">I helped students at an undisclosed, minority-serving middle school (6-8th grades) work through all types of math questions.</li>
      </ul>
    </li>
    <li class="job-title"><strong>Ranger Ambassador</strong> (2011-2012)
      <ul>
        <li class="job-description">I helped a kindergarten/1st grade teacher with teaching students who needed a little extra help learn how to add and subtract.</li>
      </ul>
    </li>
    <li class="job-title"><strong>Boy's & Girl's Club Program Staff</strong> (2009-2016)
      <ul>
        <li class="job-description">I designed and implemented games and activities for teaching and entertaining children aged 5-18.  I primarily worked with children with no place to go after school on fundamental tasks such as cooking, homework, and being aware of/respectful to others around them.</li>
      </ul>
    </li>
  </ul>  
</div>

<div class="tutorHistory">
<h3>Recently Tutored Courses</h3>
  <ul>
    <li>College Introduction to Statistics</li>
    <li>College Pre-calculus</li>
    <li>College Algebra</li>
    <li>High school Math 3</li>
    <li>Pre-calculus</li>
    <li>High School AP Calculus A/B</li>
    <li>High School AP Calculus B/C</li>
    <li>Quantitative Methods in Ecological Sciences</li>
    <li>Intermediate Mathematical Statistics</li>
    <li>High School AP Statistics</li>
    <li>Biostatistics for Nurses</li>
    <li>Middle School Algebra</li>
    <li>How to teach Statistics for Public Policy</li>
    <li>Masters of Teaching Capstone Research Project</li>
  </ul>
</div>

<div class="tutorRate">
<h3>Rate</h3>
<ul>
<li>$50/hour for most college and high school level courses.</li>
<li>Rates for children depend on the subjects and expectations of the parents. Creating lesson plans and teaching subjects will be more expensive than helping with homework.  Please reach out to address expectations and come to an agreement on hourly rate.</li>
</ul>
<p>Note: all prices are negotiable.  If you explain your situation, I'm sure we can come to an agreement on an acceptable rate.  Students paying for themselves are typically afforded the most leeway.  If you aren't sure, just ask.  My focus is on student learning, not income.</p>
<p>Second note: I don't charge for short questions that are texted or emailed to me.  If you have a quick question, send me a pic and I'll answer quickly via the same medium.  I will recommend a session if I think it will require a substantial amount of time.</p>
</div>

<div class="tutorInfo">
<h3>Additional Information</h3>
  <p>
    Kyle's tutoring style may not be entirely typical.  He will very rarely give students the answers to questions.  He does not oftentimes answer students' questions in his own terms.  Instead, he will turn questions around to the students.  He will ask them to return to their notes and review what the teacher said.  He will break the question into pieces and encourage the student to build up their understanding of the information as it relates to previously covered material.  In essence, Kyle is a teacher.  His focus is on teaching, and tutoring is on opportunity to be a 1-on-1 teacher.  
  </p>
  <p>
    Tutoring plays a big role in the development of Kyle's teaching materials.  He has learned a lot about how to not organize a class from tutoring.  He has learned a lot about what topics students struggle with in various classes.  He develops teaching resources based on what would be most beneficial to his tutees.  His goal in teaching is to make each student feel as though they are being guided through the material by an individual tutor.  And tutoring is one of the methods he practices and refines the process of achieving this goal.
  </p>

</div>







